### ISSUE TITLE
Ability to add own default values during installation

### ISSUE THREAD

**Issue by vrom911** [vrom911/hs-init#17]
Now the script uses my data in default values, that  is written in code.
Rather to dive into the script and change values there by hands I'd like to add the opportunity to change them automatically during the installation.

**Comment by axocomm** [comment]
I'm looking to get more familiar with Haskell and I'd love to give this one a try if you don't mind!

If so, may I ask if you're referring to the installation shell script (i.e. populating these values in `hs-init.hs` before copying to `~/.local/bin`) or having each run of `hs-init` allow specification, either by command line options or perhaps a configuration file, of these details?

**Comment by vrom911** [comment]
@axocomm  First of all thank you for your interest in this tool!

To clarify the issue, my plan is to add this actions to the installation script (`install`), so during the installation process you can somehow input `defaultOwner`, `defaultName`, `defaultEmail`, `defaultLicense` and `defaultGHC` and the script should replace this data directly in `hs-init` file. After installation `hs-init` should have data received on previous step  in corresponding fields. 

Adding command line option to correct this data is great idea! It will be really useful, but it's different issue, I guess. We can start with this feature now.

**Comment by axocomm** [comment]
Happy to help!

So I've got a quick solution that simply does a few `sed`s to `hs-init.hs` before moving it to `~/.local/bin`. I just have a few clarifying questions:

* For actually specifying these values, were you thinking more along the lines of a configuration file:
    ``` shell
    DEFAULT_NAME=foobar
    DEFAULT_EMAIL=foo@bar.com
    ...
    ```
    or going with command line options/environment variables?

* Should these all be required? For year and license, those could conceivably default to `date +'%Y'` and MIT respectively, but what about the owner; email; license; etc.? Perhaps just let a neglectful user give you the credit 😛 ?

**Comment by vrom911** [comment]
I think that all data should be asked interactively during work of installation script. No need for command line arguments for that. I would rather not to have any configurations files at users machine, cause I want to keep it very simple.

Also I guess none of the fields are required, and if they are not  entered during the installation we just put some template data in there. The idea of this project is that this data is asked every time during the work of the tool anyway, cause it's not permanent data, I want more flexibility and give users the opportunity to create projects with different data each time. Default values are just for making the process quick and smooth if you're using this data every time.

And thank for your comment about time. I will make a function for that directly in `hs-init.hs` which will take the current year, no need to input it during the installation :slightly_smiling_face:
