### ISSUE TITLE
[question] How to use b?

### ISSUE THREAD

**Issue by mlopes** [vrom911/hs-init#30]
I'm trying to use `b` to compile and test my project, I'm pretty new to Haskell, so I'm a bit lost with what's happening. If I run `stack build` then a compiled binary is ends up in `.stack-work/install/x86_64-osx/lts-9.9/8.0.2/bin/ghtd`, but if I run `./b` or `./b --fast`, I can't find out where the binary is being put, I've looked at the source of the file, and it doesn't seem to specify a path, so I'm a bit lost.

(sorry for the missing description on the issue, I've accidentally pressed enter while writing the title)

**Comment by vrom911** [comment]
@mlopes , first of all thank you very much for using `hs-init` for creating your project! :heart: 

`b` file is just the set of stack commands with all long arguments written for you. It's doing exactly the same that `stack` commands do and when you're using `./b` the binary will be also where you expected it to be at `.stack-work/install/x86_64-osx/lts-9.9/8.0.2/bin/ghtd`. 
`--fast` is not the valid argument for `b` script, it'll be just ignored, though in the script itself `stack build --fast` is used.
I've just cloned and tested to run `./b` on your project locally, so I can confirm that binary file is located in `.stack-work/install/x86_64-osx/lts-9.9/8.0.2/bin/ghtd`.
You can also check the directory with built project using `stack` command. In my case it is:
```bash
$ stack path --local-install-root
  /home/vrom911/haskell/ghtd/.stack-work/install/x86_64-linux-nopie/lts-9.9/8.0.2
```

**Comment by mlopes** [comment]
Hum... that is strange, I've tried making some changes to the code, running `./b`, then running the binary in `.stack-work/install/x86_64-osx/lts-9.9/8.0.2/bin/` and couldn't see any changes. I've also tried deleting the binary, and a new one wasn't created after running `./b`.

The output I get from running `./b` is:
```
$ ./b
ghtd-0.1.0.0: unregistering (components added: test:ghtd-test)
grep: empty (sub)expression
```

**Comment by vrom911** [comment]
@mlopes , could you please describe details of steps to reproduce this behavior? This needs to be investigated more properly.
@ChShersh  could you please have a look at this one, any thoughts?

**Comment by mlopes** [comment]
Ok, so, I'm not doing anything much, just running `./b` the full path of the folder where I'm doing it is: `/Users/mlopes/projects/Opensource/ghtd` (It looks like you've already looked at it, but you can see the project files here https://github.com/mlopes/ghtd).

My grep version is:
```
$ grep --version
grep (BSD grep) 2.5.1-FreeBSD
```

I tried commenting out the pipe on line 71 of my `b` file, and everything works. It looks like somehow that call to grep is breaking things for me.

**Comment by vrom911** [comment]
I have `grep (GNU grep) 2.27`. Probably that causes the issue.. Not sure.. 
What system are you using?

**Comment by mlopes** [comment]
If you’re on OS X, then you probably installed grep using brew or something similar, OS X comes with the BSD versions of the tools (Darwin is based off FreeBSD), on Linux GNU grep should be the default.
I’m replying from the phone now. Will try that and report when I have access to the computer.

**Comment by vrom911** [comment]
@mlopes thanks. Could you please try this enhanced version of `b` script : http://lpaste.net/359362
It works okay on Ubuntu so if it works for you on Mac I will replace the old version by this one.

**Comment by mlopes** [comment]
I've tried it on archlinux for now, and it works, shows the stack build output, and makes the warnings red (which I expect is the expected behaviour here?). I'll test on the Mac later today.

I wonder why not use sed to introduce ANSI codes instead of grep?

**Comment by ChShersh** [comment]
> I wonder why not use sed to introduce ANSI codes instead of grep?

@mlopes I have very little experience with `bash`. And I understand very little about this `b` script. I just copy-pasted it from another big project. Sorry, I can't be helpful here :(
But if you have any suggestions on this script improvement you can open an issue for that! :)

**Comment by mlopes** [comment]
I've tested it with the script version @vrom911 suggested above and it works on OS X (BSD grep).

**Comment by vrom911** [comment]
Thanks @mlopes . I will update `b` script with the working version and close the issue. Thanks for helping with testing!
