### ISSUE TITLE
Add b script file to projects

### ISSUE THREAD

**Issue by vrom911** [vrom911/hs-init#7]
The script should builds the project in a way that is convenient for developers.
It should pass the right flags into right places, builds the project with --fast, tidies up and highlights error messages in GHC output.

**Comment by ChShersh** [comment]
Would you mind if I complete this issue during Hacktoberfest?

**Comment by vrom911** [comment]
@ChShersh,  sure, go ahead!
Ping me if you have any questions :)

**Comment by vrom911** [comment]
Thanks, @ChShersh ! That's amazingly done :1st_place_medal:
